version: '3.7'
services:
  app:
    image:  php:${PHP_IMAGE_VERSION}
    restart: always
    depends_on:
      - db
    ports:
      - ${PORT_PHP}:80
    volumes:
      - fontes:/var/www/html
  db:
    image: mysql:${MYSQL_IMAGE_VERSION}
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD:  ${DB_USER_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - db:/var/lib/mysql
    # opcional      
    #  - ./backup-db/backup-database.sql:/var/lib/mysql

  adminer:
    image: adminer:${ADMINER_IMAGE_VERSION}
    restart: always
    ports:
      - ${PORT_ADMINER}:8080
    depends_on:
      - db
volumes:
  db:  
    driver: local
    driver_opts:
      type: nfs
      o: bind
      device: "${DOCKER_VOLUMES_DATA}/${APP_NAME}/db"
  fontes:  
    driver: local
    driver_opts:
      type: nfs
      o: bind
      device: "${DOCKER_VOLUMES_DATA}/${APP_NAME}/app"