version: '3.7'
services:
    app:
      image: recybem-bndes
      restart: always
      depends_on:
        - db
      ports:
        - ${PORT_PHP}:80
    db:
      image: mysql:latest
      restart: always
      volumes:
        - db:/var/lib/mysql
      environment:
        MYSQL_DATABASE: ${DB_NAME}
        MYSQL_USER: ${DB_USER}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    adminer:
      image: adminer:latest
      restart: always
      ports:
        - ${PORT_ADMINER}:8080
      depends_on:
        - db
volumes:
  db:  
    driver_opts:
      type: none
      o: bind
      device: "/home/git/recybem-bndes/source-code/db/"